version: "3"

services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf

    ports:
      - "80:80"
    depends_on:
      - admin
      - backend
      - frontend

  db:
    image: postgres:latest
    restart: always
    env_file:
      - development.database.env
    expose:
      - "5432"
    ports:
      - "5432:5432"

  admin:
    build:
      context: ./admin
    command: pnpm run dev
    volumes:
      - ./admin:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - "3200"

  frontend:
    build:
      context: ./frontend
    command: pnpm run dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - ./devops/cert:/usr/src/app/certificates
    expose:
      - "3100"
    links:
      - backend

  backend:
    build:
      context: ./backend
    command: air
    depends_on:
      - db
    env_file:
      - development.database.env
    environment:
      - "POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    volumes:
      - ./backend:/app
    expose:
      - "4100"
    links:
      - db
