basePath: /api/v1
definitions:
  types.Question:
    properties:
      answerCount:
        type: integer
      category:
        enum:
        - child
        - toddler
        - preteen
        - infant
        - teen
        - adult
        - household
        - relatives
        - other
        type: string
      createdAt:
        type: string
      id:
        type: string
      title:
        type: string
      viewCount:
        type: integer
      voteCount:
        type: integer
    type: object
info:
  contact:
    email: contact@mattrybin.com
    name: Matt Rybin
  description: This is an API for PeacefulParenting.ai
  title: PeacefulParenting API
  version: "1.0"
paths:
  /questions:
    get:
      consumes:
      - application/json
      description: Get a list of questions with optional sorting, range and filtering
        parameters.
      parameters:
      - description: Sort key and order ['key','order'] (default is ['id','DESC'])
        in: query
        name: sort
        type: string
      - description: Range for pagination [start, end] (default is [75, 99])
        in: query
        name: range
        type: string
      - description: Filtering by category field {'category':'value'} (default is
          {})
        in: query
        name: filter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Total-Count:
              description: Total count of questions
              type: string
          schema:
            items:
              $ref: '#/definitions/types.Question'
            type: array
      summary: Get a list of questions
      tags:
      - Questions
schemes:
- http
- https
swagger: "2.0"
