basePath: /api
info:
  contact:
    email: contact@mattrybin.com
    name: Matt Rybin
  description: This is an API for PeacefulParenting.ai
  title: PeacefulParenting API
  version: "1.0"
paths: {}
swagger: "2.0"
